# Generated by Django 6.0.4 on 2026-05-04 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, verbose_name='Davlat raqami')),
                ('brand', models.CharField(max_length=100, verbose_name='Marka/Model')),
                ('year', models.IntegerField(verbose_name='Yili')),
                ('color', models.CharField(max_length=50, verbose_name='Rang')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('texpasport', 'Texnik pasport'), ('texkorik', "Texnik ko'rik"), ('sugurta', "Avtomobil sug'urtasi"), ('haydovchi', 'Haydovchilik guvohnomasi'), ('other', 'Boshqa')], max_length=20, verbose_name='Hujjat turi')),
                ('name', models.CharField(max_length=200, verbose_name='Hujjat nomi')),
                ('issue_date', models.DateField(verbose_name='Berilgan sana')),
                ('expiry_date', models.DateField(verbose_name='Amal qilish muddati')),
                ('remind_days', models.IntegerField(default=7, verbose_name='Necha kun oldin eslatish')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.car')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="Jarima miqdori (so'm)")),
                ('fine_date', models.DateField(verbose_name='Jarima sanasi')),
                ('due_date', models.DateField(verbose_name="To'lov muddati")),
                ('reason', models.CharField(max_length=300, verbose_name='Jarima sababi')),
                ('status', models.CharField(choices=[('unpaid', "To'lanmagan"), ('paid', "To'langan"), ('disputed', "E'tiroz bildirilgan")], default='unpaid', max_length=20, verbose_name='Holati')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fines/', verbose_name='Rasm/Hujjat')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='core.car')),
            ],
            options={
                'ordering': ['-fine_date'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('document', 'Hujjat muddati'), ('fine', "Jarima to'lov muddati")], max_length=20)),
                ('message', models.TextField()),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.document')),
                ('fine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
